### PR TITLE
Gradle skeleton for Java project.

### LINKED ISSUE #24: Gradle skeleton
Build the project structure using Gradle.

### PR DESCRIPTION
**Pull request by Mohammad-nassar10**
Build the project structure using Gradle.
We should put each Java part as a directory that included a `build.gradle` file. In `setting.gradle` file, which is located in the root directory, we include all the parts.

Closes #24 
 
Signed-off-by: Mohammad-nassar10 <mohammad.nassar@ibm.com>

### CODE REVIEW

**Comment by roee88** [comment]
@Mohammad-nassar10 please link to a descriptive issue. Also, please mark as draft while this is WIP.

**Comment by roee88** [comment]
Early comments
1. There are no build.gradle files in the flight dirs
2. There is a build.gradle file in the root dir although there shouldn't be (it should have individual ones per folder and the settings.gradle should be updated to include them)
3. There is a Java-wasm-allocator directory and a java-wasm-allocator directory

**Comment by Mohammad-nassar10** [comment]
@roee88 As you said, we should add `build.gradle` files in the flight dirs and remove the `build.gradle` file from the root.
We should remove the `Java-wasm-allocator` dir.

**Comment by roee88** [comment]
> We should remove the Java-wasm-allocator dir.

Do it in this PR.

**Review by roee88 — APPROVED** [review]

**Pull request merged**
